default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  user: organizedc
  password: organizedc
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: organizedc_development

test:
  <<: *default
  database: organizedc_test

production:
  <<: *default
  database: organizedc_production
  username: organizedc
  password: <%= ENV['ORGANIZEDC_DATABASE_PASSWORD'] %>